### ISSUE TITLE
Change the name of the project to CUDALibre

### ISSUE THREAD

**Issue by marcekit** [mikex86/LibreCuda#1]
This is kind of a joke that came from a Linkedin thread...  
https://www.linkedin.com/posts/ownyourai_i-rarely-can-give-the-first-star-to-a-new-activity-7227197628705304576-ieVU?utm_source=share&utm_medium=member_desktop

I'm going on a limb here, but what the heck... Would you consider changing the name of the project to CUDALibre?  :) :) 

It's a word play with the cocktail "Cuba Libre" (https://www.liquor.com/recipes/cuba-libre/) or "Cubata" as it is called in Spain. 

You have a such a cool project! Kudos to you!

**Comment by mikex86** [comment]
nah i'm not renaming all those methods
