### ISSUE TITLE
ELF file parsing bug

### ISSUE THREAD

**Issue by CarloRamponi** [mikex86/LibreCuda#10]
Hello again,
I've noticed some problems with `libreCuModuleLoadData`.
The function works with the provided cubin file, but if I try to recompile it for a different architecture (`sm_80`, instead of the provided `sm_89`) it fails while handling the `.nv.info.*` sections:

```
Device count: 1
Handling section:  at offset 0
Handling section: .shstrtab at offset 64
Handling section: .strtab at offset 629
Handling section: .symtab at offset 1248
Handling section: .debug_frame at offset 1560
Handling section: .nv.info at offset 1896
Handling section: .nv.info.write_float_sum at offset 2040
[CUDA ERROR] at file /home/carlo/Projects/GPU/LibreCuda/src/main.cpp:52: LIBRECUDA_ERROR_INVALID_IMAGE
```

Maybe provide the command line with which you've compiled the cubin file? For me, this worked fine:
```
nvcc -std=c++11 -arch sm_89 write_float.cu -o write_float.cubin --cubin
```

But also compiling for the right architecture is not enough. If I slightly modify the kernel's code, such as adding a `printf`:

```c++
// [...]

extern "C" __global__ void write_float_sum(float *dst, short a, float b) {
    *dst = (a + b);
    printf("a: %d, b: %f, dst: %f\n", a, b, *dst);
}
```

Then LibreCuda fails with a segmentation fault:

```
Device count: 1
Handling section:  at offset 0
Handling section: .shstrtab at offset 64
Handling section: .strtab at offset 703
Handling section: .symtab at offset 1408
Handling section: .debug_frame at offset 1816
Handling section: .nv.info at offset 2152
[1]    26662 segmentation fault (core dumped)  ./LibreCuda
```

The exception happens on these lines because `target` is a null pointer:

```c++
if ((type & 0xffff) == EIATTR_MIN_STACK_SIZE) {
    auto target = elf_reader.sections[func + 5]; // ignores null section, .shstrtab, .strtab, .symtab & .debug_frame
    auto target_name = target->get_name(); // <-- SIGSEGV
```

I see that this has been implemented recently so I guess it is still WIP.

_P.S.: I'd like to ask you a few questions, but I can't find your email address, if you are available you can send me an email and I will get back to you, my address is on my github profile_

**Comment by mikex86** [comment]
I can reproduce the issue with
```
nvcc -ptx -std=c++11 -arch sm_80 write_float.cu -o write_float.ptx
ptxas -arch sm_80 write_float.ptx -o write_float.cubin
```

The issue is 
```cpp
                   default: {
                        // TODO: This isn't strictly correct,
                        //  it just means we don't know the attribute yet.
                        //  But we HAVE to abort here, because of the variable length nature of attributes
                        LIBRECUDA_FAIL(LIBRECUDA_ERROR_INVALID_IMAGE)
                    }
```

The binary contains a `EIATTR_SW2861232_WAR` attribute, which was previously unknown. As the code already states, if we encounter an unknown attribute we have to abort to avoid misinterpreting subsequent attributes and causing more damage.

This is the reason for the sm_89 bug.

The SIGSEGV bug is currently being debugged.

If you find the time, maybe confirm if your sm_80 test scenario works now.

**Comment by CarloRamponi** [comment]
Hello @mikex86,
thanks for the quick response, I can confirm that sm_80 binaries now are being correctly parsed.
The other bug remains.

**Comment by CarloRamponi** [comment]
Maybe an OT question: is there a way to use `cuda-gdb` with LibreCuda to debug kernel execution?

_P.S.: I have some ideas on how to augment this project, but I need to check the feasibility with you first, please contact me via email if you are interested :)_

**Comment by mikex86** [comment]
The assertion that the index value obtained from a EIATTR_MIN_STACK_SIZE nvinfo attribute is infact 5 less than the section index it refers to is wrong.

```asm
//----- nvinfo : EIATTR_MIN_STACK_SIZE
	.align		4
.L_14:
        /*0054*/ 	.byte	0x04, 0x12
        /*0056*/ 	.short	(.L_16 - .L_15)
	.align		4
.L_15:
        /*0058*/ 	.word	index@(write_float_sum)
        /*005c*/ 	.word	0x00000018
```

This is indexing into a different list, as sections that are next to each other are somtimes referred to with +2 difference, ruling out that it is a constant offset.
The index actually refers to the symbol table, where printf is inserted after the function that uses it, causing this shift.

The use of printf also causes the usage of previously unknown nvinfo attributes:
`EIATTR_EXTERNS` and `EIATTR_SYSCALL_OFFSETS`.
The length of `EIATTR_MAXREG_COUNT` was also incorrect, resulting in misinterpretation of subsequent attributes.

There also was an incorrect assertion that nv constants always have to refer to functions.

While the ELF parsing logic now no longer causes issues, the kernel itself still never completes execution. `printf` from inside the kernel seems to require further setup to complete correctly.

I will mark this issue as complete, feel free to open an issue regarding the `printf` problem in isolation.

**Comment by mikex86** [comment]
Regarding cuda-gdb, this is a whole other can of worms, feel free to open an issue.

Also, freel free to shoot me a Twitter DM, as my email is on enough spam lists already and being available for web scraping probably won't make this any better 🙃 

https://x.com/mike64_t
