### ISSUE TITLE
"Impersonate" CUDA Driver Like SCALE

### ISSUE THREAD

**Issue by TheFloatingBrain** [mikex86/LibreCuda#18]
Any plans to be a drop in replacement for CUDA drivers like [SCALE can](https://docs.scale-lang.com/#how-does-it-work)?

```
SCALE has several key innovations compared to other cross-platform GPGPU solutions:

    * SCALE accepts CUDA programs as-is. No need to port them to another language. This is true even if your program uses inline PTX asm.
    * The SCALE compiler accepts the same command-line options and CUDA dialect as nvcc, serving as a drop-in replacement.
    * "Impersonates" an installation of the NVIDIA CUDA Toolkit, so existing build tools and scripts like cmake just work.
```

**Comment by mikex86** [comment]
The goal of LibreCUDA is not to full-on impersonate a Cuda installation, but it is something you can statically link against and the resulting application will have zero runtime dependencies. No cuda installation required.

**Comment by TheFloatingBrain** [comment]
So it is not intended to run a pre-compiled binary that calls to the CUDA API?

**Comment by mikex86** [comment]
It just means you can. LibreCuda has a slightly different motiviation. It is not suppose to be a 1 to 1 drop in replacement. That rarely ends well. Instead it is very cuda-like, and sometimes even gives you features normal cuda doesn't support, such as multiple async kernel launches on the same stream without sequentialization. LibreCuda is for the enthusiast low level kernel developer that wants to optimize close to the hardware, but is willing to deal with a few minor differences of implementation.

**Comment by TheFloatingBrain** [comment]
> It just means you can. 


By dynamic linking?

> LibreCuda has a slightly different motiviation. It is not suppose to be a 1 to 1 drop in replacement. That rarely ends well.

Yep haha


> Instead it is very cuda-like, and sometimes even gives you features normal cuda doesn't support, such as multiple async kernel launches on the same stream without sequentialization. LibreCuda is for the enthusiast low level kernel developer that wants to optimize close to the hardware, but is willing to deal with a few minor differences of implementation.

I think I understand your use case a bit better now

**Comment by mikex86** [comment]
You can of course also dynamically link against librecuda, that is not the issue. You will just not get something that will run when linking against real cuda.

**Comment by TheFloatingBrain** [comment]
Understood, thank you for taking the time to answer! :)
