### ISSUE TITLE
Consider collaboration with the cuda-api-wrapperd library

### ISSUE THREAD

**Issue by eyalroz** [mikex86/LibreCuda#2]
Have you had a look at [cuda-api-wrappers](https://github.com/eyalroz/cuda-api-wrappers)? It's a 3-BSD-licensed header-only library of wrappers around the CUDA drivers (and other CUDA facilities), which offers the modern-C++ interface to those APIs. I'm the author... 

I think it might be interesting for our projects to collaborate. I'd try emailing you, but you've not provided an address; you are welcome to drop me a line.

**Comment by mikex86** [comment]
Hmm... There's just this problem that I've already broken backwards compat with the CUDA api surface. Eg. adding length parameters where there clearly should be, or making streams work more like typical command buffers, where you have to explicitly submit your built up queue.

libreCuStreamCommence and libreCuStreamAwait don't actually exist in the cuda driver API.

**Comment by eyalroz** [comment]
> Hmm... There's just this problem that I've already broken backwards compat with the CUDA api surface. 

Let's talk about this. Remember that the CUDA API itself changes from version to version, sometimes breaking backwards compat (e.g. by removing API calls).

**Comment by mikex86** [comment]
Maybe, I was talking about purely the super stable stuff like the CUDA driver api.
Remember, this project currently can
1. alloc memory
2. launch a cuda kernel only if all the arguments are pointers
3. free memory

That's basically it. There is not even a real memcopy yet, there is just host mapped memory.
I think it's a little early to start talking about something that implies feature parity - wrapping with a common abstraction.
It's far from production ready by any stretch of the definition.

I mean you are welcome to wrap the like 3 functions that exist, but I'm not sure what the value in that is as of now.
I will try to implement as many functions as possible, but the primary goal of LibreCUDA is to be a minimalistic CUDA replacement for projects like llm.c, where all you basically do is alloc memory and launch kernels.

As of right now I'm having a hard time imagining how this collab would look like, so feel free to clarify what your goals here would be.

**Comment by eyalroz** [comment]
I realize the project is at a very early stage. I actually meant that as it matures and begins to be more usable, the possibility of using something like cuda-api-wrappers around it becomes more interesting. When and if you think you're getting there - or if you think my experience with the wrappers might be interesting for your design considerations - do write me up :-)

**Comment by mikex86** [comment]
Thanks for the offer, will do
